version: '3.8'
services: 
    db:
      image: mysql:5.7
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=root_pwd
        - MYSQL_DATABASE=isearch
      ports:
        - 3306:3306
      volumes:
        - .data:/var/lib/mysql

volumes:
  db: